# Exploring conversion {#conversion}

**The main question we explore on this page: how much of the historic ecosystems have been converted to a different land use (e.g., agriculture).**  

## The fine print
While this assessment is illustrative, it is important to note that the methods used to create the BpS and EVT datasets are substantially different, and LANDFIRE datasets are not made for assessing small areas.  Please review.  In the exercise we will focus on the coarsest classifications.  If you need to work at the finer classification levels proceed with caution!

## Pivot table work
Working in the "Conversion" worksheet:

1. Check the "GROUPVEG" then the "EVT_PHYS" fields to add them to the Pivot Table.  Make sure that GROUPVEG is the leftmost column.  If not drag that field to the top in the Rows pane.
2. In the cell above the "GROUPVEG" field header type "past"; in the cell above the "EVT_PHYS" type "present".
3. If you fancy click the dropdown in the "GROUPVEG" header.  Here you can remove types.  Let's remove "Barren-Rock/Sand/Clay".
4. Check the "ACRES" field to add it to the Pivot Table.
5. Explore.  Of what was historically mapped as CONIFER, what's the biggest non-CONIFER type today?
6. Switch the order of the fields by dragging "EVT_PHYS" to the top of the Rows pane.  Which GROUPVEG type was most converted to "Developed"?


## Visual exploration for fun. 

Sometimes patterns emerge from visuals.  Below is a [Sankey Diagram](https://en.wikipedia.org/wiki/Sankey_diagram) generated in R (can also be created in Excel we hear.  See instructions [here](https://mychartguide.com/how-to-draw-sankey-diagram-in-excel/)).  On the left are the historical ecosystems, on the right current ecosystems and flow bands.  The width of the bands is proportional to the flow rate.  Some potential interpretations, partially based on the chart, partially based on local knowledge:

* There is more northern hardwoods mapped today than historically.  This could be due to "simplification" of ecosystems that have some shared species.  For example, many conifers have been removed and deer present a challenge for regeneration.  One hypothesis would be that due to logging and deer the "Pine-Hemlock-Hardwood-Forest" has been essentially converted to "Northern Hardwoods".
* It might be more illuminating to group some types together, such as the "Recently Logged" types.
* LANDFIRE has mapped potential change of the wetlands to other types.  This could be due to mapping errors, or due to alterations in hydrology because of roads perhaps.  More investigation is warranted.

Click [here](https://rswaty.github.io/landfireFSC/sankey.html) to view diagram in your web browser. 

```{r sankey, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=8}

library(networkD3)
library(dplyr)
library(readr)
library(dplyr)

data <- read_csv("bps2evt.csv")

nodes <- data.frame(
  name=c(as.character(data$source), 
         as.character(data$target)) %>% unique())


data$IDsource <- match(data$source, nodes$name)-1 
data$IDtarget <- match(data$target, nodes$name)-1

# Make the Network
snky2 <- sankeyNetwork(Links = data, 
                       Nodes = nodes,
                       Source = "IDsource", 
                       Target = "IDtarget",
                       Value = "value", 
                       NodeID = "name", 
                       fontSize=14,
                       iterations = 0,
                       sinksRight=FALSE)

snky2

# save the widget
library(htmlwidgets)
saveWidget(snky2, "sankey.html")


```

